name: Schoolwell Frontend Dev CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: schoolwell
        tags: latest
        dockerfile: Dockerfile
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
 # deployment:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: deploy
   #     run: |
   #       curl -sS -d 'auth_key=${{ secrets.DEPLOY_AUTH_KEY }}' \
  #        -d 'name=schoolwell_frontend_dev' -d 'image=ghcr.io/africasgeeks/website_frontend:dev_latest' \
  #        -d 'network=bridge' -d 'v_map=no' -d 'port_ex=127.0.0.1:2002' -d 'port_in=80' \
    #      -X POST -H 'Content-Type: application/x-www-form-urlencoded' '${{ secrets.DEPLOY_URL }}'